#Here the Goal is to find the complement of the given DNA strand from 5' end to 3' end
DNA_seq="AAGGGTGCGTAGCTAGAATACTCTGCCTAATTCTGATGCGACTGAACTACGAACACGGCCATTGATCGCGACACCAATATCCAACCAGTAGATATCCGCATACCTGCACCGAACCTACCTTACCCGCAGCTAACCAGCCCCGAGGACTGTGGAAAATAAATTAAAAGGGAGCACCGTAACCCGCGCGCGTTTTCCGATGAACCCGCATTATATGAAACACGGTTTCCAAAACCCAGACGCACGGCCCTAAAGTGGAGTATTCTTATCGCGTGACTACGTCTCCCCCCGGTTGAAGGATTTAATGCACGTCGATGTTGAGTAACGGGATGTCCTTAACAGAACCAGGTATATGCGCGGTAGCCAGAGGGATGAATGCGTTCTTCTTTCCTGGCTTGAGGTCTCAGAGAAGGCACCGTACTTACGAGCAATCACAACATAAATGGGGCATGGACAGTTAGGAATCATCTTAGCGCGAATTTGGGAATTCACAGCACCTGCCCTTGTACAAATCTTAACAACGCGACAAACAACCTCATCTAGGGAGCGTTCCATTGGGATAAGATGGCAGGCGCCGGGAACAATCATGACTAGACCGAACGCCTTTGCGACATTCACCACACAAGATTCCCCGGGGACTCACACTGTCAGCGTGCCATTGACTGTTTCACGAGGGAGTGGTTAGTTCTGCCTTCCGTCTGATACCTCATCGTTCGTCGAGAGGGAGTGACCAGGGCACCGGCATAGAATTCGATCAATGCAGCAATGCGGAGCAGGGCGAAGAGTCTCACCGTGCCTGACGCGACG"
# Separating all the bases from the DNA sequence
bases=list(DNA_seq)
#Creating a list to find a complementary 3' to 5' strand
rev_seq=[]
for base in bases:
    if base=='A':
        rev_seq.append('T')
    elif base=='T':
        rev_seq.append('A')
    elif base=='G':
        rev_seq.append('C')
    elif base=='C':
        rev_seq.append('G')
#reverse_code will be the seq from 3' to 5'
reverse_code=''.join(rev_seq)
#We need the seq from 5' to 3'
answer=reverse_code[::-1]
print(answer)
