def mrna_seq(protein_seq):
    #Mapping each amino acid with codon frequency
    codon_counts = {
        'A': 4, 'C': 2, 'D': 2, 'E': 2, 'F': 2, 'G': 4, 'H': 2, 'I': 3, 'K': 2, 'L': 6,
        'M': 1, 'N': 2, 'P': 4, 'Q': 2, 'R': 6, 'S': 6, 'T': 4, 'V': 4, 'W': 1, 'Y': 2
    }
    #starting with 3 to consider stop codon
    total_combinations=3
    MOD=1000000
    #Taking each protein from protein_seq
    for aa in protein_seq:
        if aa in codon_counts:
            total_combinations=(total_combinations*codon_counts[aa])%MOD
    return total_combinations
protein="MAPCISGRWQKCLPYTYWMFGNRIYQCGVMGWHDMPWLTNKQFALCYACMGVYDVQSHKGRGRSWIWAIIFAGGHKVKLNCNDAKQTYLLWPENHCGGYDNIHAASHCFCTDSKFVATNHWTKGSIMLVWDPYVQKKKIHDYVRALVRYACRNAKLTMISYAPVCQEGLMDKNARHFDHYQHNWNILMTPWPDVLQWWHTEPYCCSLRESVNAMWRHMWQLQNASFRHMHVQMNMYAASEWQDSSLYFWFANGKMRHGYIKTESHNFSYILSEIRRWPPWIFNQWLPYYCVGDIMTRCIPYQAFMLAHKQKDAPNHDTANIAIDRCRNQTHMIRHDYHIRKEDGWLFIYWVGDKYRDNFLIFTVATVMHMAGEWQVRHNVSRGKWRRRTFGEWGVNHYHDQNQGVWHNTDVCCQAGWSMPLVMARYLPRMADYHIRHDHDVQNDCSTWTYVQALQKFRIKLHANMKMMPDWYHDKCGRYDRDWMCNSWPGFFNSPTGTCNVEWLGLKWHHTMQLDWKNTIRDNRHMKPLARHHNIMKEAHHHQWRGLWIWHPFTGNMSASHAYLTATNKQADHRSFNLRRMTNMGTLYQWRLCGDLNNRRDLDCLYANWNLNIKKPTQNECHLIAWILWMGNQSSHDTTKIMVGGTDICFLKNLDQCHWALYSQCFDMLWDRSLNVHACIRAFDFDAAHMWEPIYGNINWVTYEAKYCHDNGQDFSIRHFSHKAFEWAVYEDWFWPCKVDEGIALMHRLFPFFKEHVFMILWRNFREHNPLPTQFRYFMFSYKRSVKTHHSAARWDPFFSLIYWKTLDNLPDNWGFQMTKMHSLRVQGDYMVIEFGDGYNDRAKPWPCDVLYWYNYCNTWNYWHLQDCHINKFTVWQKWMDQFHMQKAMIGRISQCVQVEDKTEWRVGVWPRKSACQWHCSADAIVCIVPKCMYVLAIKMGHKNMWSSPCWIEQDEFHWFTCISAMQYPQGQWVPVHCFLRYQKKKCCGDVDMVDVTDPN"
print(mrna_seq(protein))