DNA_strand = "CGCGACATTGTTATGATGGGTATACCTGAGCCACTCAATGTTCCGAGGACAAGGTTACTTATAGCACGCACGAAGTCACGTTGCCCCGCACAATGCTAGGTTACGAGCCAAAACAGATGTCCGGGGAATAGCGGGATGGCGGGTCTCAAATAGAGTACGGTGCCTAATTCATGTTGGGAAGTTCCGCTAGCTAGGATGATGACATAGACGAAAGCGTGATGTGACTCACCCATTTCCCATTAGCACAGAATCGTCCCCATTAGGTACCTCTTTGTTGATCAATCTGAACCGCCCTTTGACGATTAGCCAAAAATCGGACGTCCTTAAGTCGGTAAGAGGTACTTATAATCTCACTCAGTTTGCTTGGTCCTACCTGGCCTTTTATTCAGGACCGGGGCACGGTTCTGATACCGATTAGCAAACAATATTGTTTACAAGTCACTATGCAGACCTTGCCGGTACACAGGAGAATGTTCTATCTCTAGACGCGCAGGCGCACGTCATGCGGTGTGGAATTGCCACTTCCGTGCCTAACAATCGTGGTAAGGCGTGCGGTTCCTCGGGGGTTGTATCCAAAGCCGCTTCGCGTTCATCCAGTCGAAGCGATACGGGTATCCGACCTGACTGCTAATAAAACGGTCTCGAACTTAACTCAAGTTAAGACCCAAAGCTTCAAGAGTGCGTAGGTCATAGCCATCGTCTGTCTATAGGATGATTTAATGCTCCAAATCGGGTGCCCCGGTCAGTCATCTGCCACAATCGTAGTTATCGACCCGGCACTTCTAACAGTCCAATGAAAAGGGAGTGCCAGCCAATGGCGCGGTCCCGCGGTACTGCGCTTTGCATAACGCG"
# To make a reversed strand
def revcomp(s):
    comp = {'A':'T','T':'A','G':'C','C':'G'}
    return ''.join(comp[b] for b in reversed(s))
n = len(DNA_strand)
# Introducing 2 variables i (For reporting the location of the part) and length(For breaking the strand in parts)
for i in range(n):
    for length in range(4, 13):
        if i + length <= n:
            sub = DNA_strand[i:i+length]
            if sub == revcomp(sub):
                print(i+1, length)