DNA_seq="AAGGGTGCGTAGCTAGAATACTCTGCCTAATTCTGATGCGACTGAACTACGAACACGGCCATTGATCGCGACACCAATATCCAACCAGTAGATATCCGCATACCTGCACCGAACCTACCTTACCCGCAGCTAACCAGCCCCGAGGACTGTGGAAAATAAATTAAAAGGGAGCACCGTAACCCGCGCGCGTTTTCCGATGAACCCGCATTATATGAAACACGGTTTCCAAAACCCAGACGCACGGCCCTAAAGTGGAGTATTCTTATCGCGTGACTACGTCTCCCCCCGGTTGAAGGATTTAATGCACGTCGATGTTGAGTAACGGGATGTCCTTAACAGAACCAGGTATATGCGCGGTAGCCAGAGGGATGAATGCGTTCTTCTTTCCTGGCTTGAGGTCTCAGAGAAGGCACCGTACTTACGAGCAATCACAACATAAATGGGGCATGGACAGTTAGGAATCATCTTAGCGCGAATTTGGGAATTCACAGCACCTGCCCTTGTACAAATCTTAACAACGCGACAAACAACCTCATCTAGGGAGCGTTCCATTGGGATAAGATGGCAGGCGCCGGGAACAATCATGACTAGACCGAACGCCTTTGCGACATTCACCACACAAGATTCCCCGGGGACTCACACTGTCAGCGTGCCATTGACTGTTTCACGAGGGAGTGGTTAGTTCTGCCTTCCGTCTGATACCTCATCGTTCGTCGAGAGGGAGTGACCAGGGCACCGGCATAGAATTCGATCAATGCAGCAATGCGGAGCAGGGCGAAGAGTCTCACCGTGCCTGACGCGACG"
bases=list(DNA_seq)
rev_seq=[]
for base in bases:
    if base=='A':
        rev_seq.append('T')
    elif base=='T':
        rev_seq.append('A')
    elif base=='G':
        rev_seq.append('C')
    elif base=='C':
        rev_seq.append('G')
#reverse_code will be the seq from 3' to 5'
reverse_code=''.join(rev_seq)
#We need the seq from 5' to 3'
answer=reverse_code[::-1]
print(answer)